<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>MSZDialougeManager</RootNamespace>
    <AssemblyName>MSZDialougeManager</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <Deterministic>true</Deterministic>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="msz.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	<PackageReference Include="System.Speech" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Miside Zero Dialogue Override">
      <HintPath>Miside Zero Dialogue Override.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>